### ISSUE TITLE
[JC/Week4] Swift에서 추천하는 DataBase는 무엇이 있나요?

### ISSUE THREAD

**Issue by jayn2u** [SSUMC-6th/iOS_A#19]
# Swift에서 추천하는 DataBase는 무엇이 있나요?

## 배경
`Authentication` 기능을 구현하기 위해서  처음 `Firebase`로 작업을 시작했습니다. 그러던 중 오늘 친구와 이야기 하던 중 `Supabase`도 추천하더군요. 그래서 궁금했습니다. iOS 앱 개발에서 추천하는 Database는 어떤 제품을 사용하는지 궁금합니다.

**Comment by jayn2u** [comment]
# 추가질문

- DataBase를 고르는 기준이 있나요? 소프트웨어 제품 역시 일종의 상품으로서 수요가 있어야 선택하는 것이고 매력적인 요소들에 의해서 소프트웨어 제품을 고르는 것이라고 생각합니다. 많은 기업들에서 운영하는 B2B 소프트웨어를 골랐던 경험이 궁금해요.

**Comment by kimsoomin20221789** [comment]
보통 토이프로젝트를 할때는 프론트가 서비스형 백엔드(Firebase나 Supabase)를 사용할 수 있기는 하지만, 큰 협업을 할때는 백엔드팀에서 Custom하게 서버를 구축한 다음에 프로트 팀은 API를 전달받습니다.
혹시 어떤 기능을 위한 DataBase인지 여쭤봐도 될까요?

**Comment by kimsoomin20221789** [comment]
> # Swift에서 추천하는 DataBase는 무엇이 있나요?
> ## 배경
> `Authentication` 기능을 구현하기 위해서 처음 `Firebase`로 작업을 시작했습니다. 그러던 중 오늘 친구와 이야기 하던 중 `Supabase`도 추천하더군요. 그래서 궁금했습니다. iOS 앱 개발에서 추천하는 Database는 어떤 제품을 사용하는지 궁금합니다.

보통 토이프로젝트를 할때는 프론트가 서비스형 백엔드(Firebase나 Supabase)를 사용할 수 있기는 하지만, 큰 협업을 할때는 백엔드팀에서 Custom하게 서버를 구축한 다음에 프로트 팀은 API를 전달받습니다.
혹시 어떤 기능을 위한 DataBase인지 여쭤봐도 될까요?

**Comment by kimsoomin20221789** [comment]
> # 추가질문
> * DataBase를 고르는 기준이 있나요? 소프트웨어 제품 역시 일종의 상품으로서 수요가 있어야 선택하는 것이고 매력적인 요소들에 의해서 소프트웨어 제품을 고르는 것이라고 생각합니다. 많은 기업들에서 운영하는 B2B 소프트웨어를 골랐던 경험이 궁금해요.

위의 질문과 같이 DB는 백엔드팀이 선택하여 서버를 구축하는데, 데이터의 형식(NoSQL, MySQL)이나 운영비용, 사용자 쿼리 수 등을 고려하여 DB를 선택하긴 하는데, 답변이 되셨을까요..?

그리고 B2B 소프트웨어에 대해서는 잘모르겠는데, 예시로 무엇이 있나요???

**Comment by jayn2u** [comment]
> > # Swift에서 추천하는 DataBase는 무엇이 있나요?
> > ## 배경
> > `Authentication` 기능을 구현하기 위해서 처음 `Firebase`로 작업을 시작했습니다. 그러던 중 오늘 친구와 이야기 하던 중 `Supabase`도 추천하더군요. 그래서 궁금했습니다. iOS 앱 개발에서 추천하는 Database는 어떤 제품을 사용하는지 궁금합니다.
> 
> 보통 토이프로젝트를 할때는 프론트가 서비스형 백엔드(Firebase나 Supabase)를 사용할 수 있기는 하지만, 큰 협업을 할때는 백엔드팀에서 Custom하게 서버를 구축한 다음에 프로트 팀은 API를 전달받습니다. 혹시 어떤 기능을 위한 DataBase인지 여쭤봐도 될까요?

아직 특별하게 어떤 기능을 구현하기 위해서 사용하는 것은 아니고, 미션을 하다보니 `사용자 인증` 기능을 한 번 구현해보려고 했어! 그리고 사용자 인증 기능을 영어로 `User Authentication`이라고 하더라구. 우선은 `Firebase`로 작업을 해보는 중이야. `Supabase`는 친구가 소개해준 Database라서 한 번 구경해보는 과정에서 위와 같은 생각이 들었거든.

큰 협업을 하는 과정에서 백엔드팀이 하는 일이 어떤 것인지 느낌을 알겠어. 생각을 나누어주어서 고마워!

**Comment by jayn2u** [comment]
> > # 추가질문
> > 
> > * DataBase를 고르는 기준이 있나요? 소프트웨어 제품 역시 일종의 상품으로서 수요가 있어야 선택하는 것이고 매력적인 요소들에 의해서 소프트웨어 제품을 고르는 것이라고 생각합니다. 많은 기업들에서 운영하는 B2B 소프트웨어를 골랐던 경험이 궁금해요.
> 
> 위의 질문과 같이 DB는 백엔드팀이 선택하여 서버를 구축하는데, 데이터의 형식(NoSQL, MySQL)이나 운영비용, 사용자 쿼리 수 등을 고려하여 DB를 선택하긴 하는데, 답변이 되셨을까요..?
> 
> 그리고 B2B 소프트웨어에 대해서는 잘모르겠는데, 예시로 무엇이 있나요???

아하! B2B 소프트웨어는 말이 어려울 뿐이지, 기업에서 제공하는 Database를 전부 B2B 소프트웨어라고 부르는 것 같아. 그래서 나도 일괄적으로 묶어서 명칭하기 위해서 사용했던 단어였어! 그렇게 크게 어렵게 생각하지 않아도 좋을 것 같아.
