### ISSUE TITLE
[week4] Token & UserDefaults

### ISSUE THREAD

**Issue by kimsoomin20221789** [SSUMC-6th/iOS_A#30]
- [ ] 회원가입 버튼 클릭 시, UserDefault 사용해서 회원정보 저장
- [ ] 회원가입 버튼 클릭 시, 로그인 후, 자동로그인 알림창 띄우기
- [ ] UserDefault 사용해서 자동로그인 구현하기 (다시 실행시킬때 로그인화면x 홈화면o)

**Comment by jayn2u** [comment]
4주차 미션 끝!
