### ISSUE TITLE
[week6] Layout with SwiftUI

### ISSUE THREAD

**Issue by kimsoomin20221789** [SSUMC-6th/iOS_A#45]
<img width="235" alt="스크린샷 2024-05-14 오후 5 37 49" src="https://github.com/SSUMC-6th/iOS_A/assets/125457422/e78cb8e7-3b02-4217-89aa-978c6da0b7fe">

> 절대 똑같이 구현하라는 말 아닙니다!!  위 사진과 같은 구성(버튼의 개수, 위치) 으로만 만들어주시고 버튼 내의 세부적인 것은 Text정도만 넣어주세요!
- [ ] 탭바 만들기

> 탭바의 첫번째 뷰에 적용할 사항들

- [ ]         `Button` 사용해보기
- [ ]         `Text` 사용해보기
- [ ]         `VStack` 또는 `HStack` 사용해보기

**Comment by jayn2u** [comment]
6주차 미션 끝!
